#!/usr/bin/env node
/**
 * Generate the public catalogue the web page reads.
 *
 * GitHub Pages serves `docs/` as the site root, so the page cannot reach
 * `../art/looks.json`. Rather than duplicate the declaration into the page — two
 * copies that would drift — this writes the public subset of it into the site
 * folder, and the page fetches that.
 *
 *   npm run build:site
 *
 * Only fields that are safe and useful in public are copied: identities, names in
 * both languages, the theme key and whether a look animates. Rights lines and
 * source URLs stay in the repository.
 *
 * The English wording (`nameEn`, `roleEn`, `taglineEn`) lives in the same
 * declaration rather than in the page, so a look added for the plugin gets an
 * English name in the console by editing one file — and a missing translation
 * falls back to the plugin's own copy instead of rendering `undefined`.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const declaration = JSON.parse(readFileSync(join(root, "art", "looks.json"), "utf8"));
const manifest = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));

/** The generated art index, when it exists, says which looks actually animate. */
let indexed = { looks: [] };
try {
  indexed = JSON.parse(readFileSync(join(root, "art", "index.json"), "utf8"));
} catch {
  /* no index yet — the page falls back to the declaration's own frame lists */
}

const animated = new Set(indexed.looks.filter((look) => look.animated).map((look) => look.id));

const catalog = {
  version: manifest.version,
  repository: "https://github.com/ZYAONS/dsh-plugin-mascot",
  characters: declaration.characters.map((character) => ({
    id: character.id,
    name: character.name,
    nameEn: character.latin,
    latin: character.latin,
    role: character.role,
    roleEn: character.roleEn ?? character.role,
    tagline: character.tagline,
    taglineEn: character.taglineEn ?? character.tagline,
    theme: character.theme,
    looks: declaration.looks
      .filter((look) => look.character === character.id)
      .map((look) => look.id),
  })),
  looks: declaration.looks.map((look) => ({
    id: look.id,
    character: look.character,
    name: look.name,
    nameEn: look.nameEn ?? look.name,
    animated: animated.has(look.id) || (look.frames ?? []).length > 1,
  })),
};

const target = join(root, "docs", "site", "catalog.json");
writeFileSync(target, `${JSON.stringify(catalog, null, 2)}\n`);
console.log(`build-site: wrote ${target} (${String(catalog.characters.length)} characters, ${String(catalog.looks.length)} looks)`);

//#region rig extraction
/**
 * Lift the rig out of the plugin's browser bundle.
 *
 * The console previews the mascot with the very same skeleton the plugin runs, and
 * the plugin's half is a single file by necessity (the browser module loader takes
 * one registration per package). Rather than keep a second copy of the geometry,
 * this copies the regions verbatim — the same "generate from one source" move as
 * `catalog.json`, and `check-site` fails when the copy goes stale.
 *
 * The three regions are self-contained: they reference each other, `document` and
 * `Math`, and nothing from the surrounding closure.
 */
function region(source, name) {
  const start = source.indexOf(`//#region ${name}\n`);
  if (start < 0) throw new Error(`build-site: lib/client.js has no #region ${name}`);
  const end = source.indexOf("//#endregion", start);
  if (end < 0) throw new Error(`build-site: #region ${name} is never closed`);
  return source
    .slice(start, end)
    .split("\n")
    .map((line) => (line.startsWith("\t\t") ? line.slice(2) : line))
    .join("\n")
    .trimEnd();
}

const client = readFileSync(join(root, "lib", "client.js"), "utf8");
const rigModule = [
  "/**",
  " * The skeleton: automatic rigging, linear blend skinning and idle posing.",
  " *",
  " * GENERATED by scripts/build-site.mjs from the #region blocks of lib/client.js.",
  " * Do not edit here — edit the plugin and run `npm run build:site`.",
  " */",
  "",
  region(client, "skeleton"),
  "",
  region(client, "skinning"),
  "",
  region(client, "pose"),
  "",
  "/** Why the last rig attempt was abandoned, or null when it never was. */",
  "function rigStatus() {",
  "  return lastRigError ?? null;",
  "}",
  "",
  "export { RIG, findNeck, buildRig, createSkinner, poseRig, rigStatus };",
  "",
].join("\n");
const rigTarget = join(root, "docs", "site", "rig.js");
writeFileSync(rigTarget, rigModule);
console.log(`build-site: wrote ${rigTarget} (${String(rigModule.length)} bytes, extracted from lib/client.js)`);
//#endregion

