#!/usr/bin/env node
/**
 * 把 art/motion.json 的实测曲线压成一段字面量，写进 lib/client.js。
 *
 * 为什么要有这一步：插件的浏览器半边必须是**一个自包含的文件**（模块加载器一个包只收一次
 * 注册），所以它读不到 art/motion.json。曲线得进去。而抄一遍就容易漂 —— 所以这段字面量是
 * **生成**的，不是手写的，`npm run measure:motion` 之后跟着跑一次即可。
 *
 * 用法：node scripts/motion-literal.mjs
 */

import { readFileSync, writeFileSync } from "node:fs";

const START = "\t\t/* MOTION-START */";
const END = "\t\t/* MOTION-END */";

const motion = JSON.parse(readFileSync("art/motion.json", "utf8"));

/** 每 n 个采样取一个，够用且省一半以上体积。 */
const stride = { idle: 3, greet: 2 };

/** 把一串采样按 stride 抽稀，最后一点始终保留，否则循环不闭合。 */
function thin(values, step) {
  const out = [];
  for (let i = 0; i < values.length; i += step) out.push(Math.round(values[i] * 100) / 100);
  const last = Math.round(values[values.length - 1] * 100) / 100;
  if (out[out.length - 1] !== last) out.push(last);
  return out;
}

/**
 * One entry per character.
 *
 * The file used to hold a single character's measurement with no wrapper; reading that as
 * 可露希尔's entry is the migration, and it only has to happen once.
 */
const characters = motion.characters ?? { closure: motion };
const defaultCharacter = characters.closure !== undefined ? "closure" : Object.keys(characters)[0];

const channels = ["waist", "chest", "head"];
const lines = [];
lines.push(START);
lines.push("\t\t/**");
lines.push("\t\t * The idle and the greeting, measured from the official chibi rather than");
lines.push("\t\t * invented, one bundle per character. GENERATED by scripts/motion-literal.mjs");
lines.push("\t\t * from art/motion.json — edit neither by hand; re-run `npm run measure:motion`");
lines.push("\t\t * and then that script.");
lines.push("\t\t *");
lines.push("\t\t * Values are bone rotations in degrees, sampled every `step` seconds and");
lines.push("\t\t * looped. `waist` drives the spine, and `chest + head` accumulate into the");
lines.push("\t\t * neck, which is how the game's own chain adds up: each bone is relative to");
lines.push("\t\t * its parent and this rig has no separate chest.");
lines.push("\t\t *");
lines.push("\t\t * Keyed by character, because that is what the client has when it draws. A");
lines.push("\t\t * character with no entry falls back to MOTION_DEFAULT rather than to nothing:");
lines.push("\t\t * a still figure is a worse failure than a borrowed idle.");
lines.push("\t\t */");
lines.push("\t\tconst SPINE_MOTION = {");

for (const [character, bundle] of Object.entries(characters)) {
  lines.push(`\t\t\t${character}: {`);
  for (const [key, strideFor] of Object.entries(stride)) {
    const animation = bundle.animations[key];
    if (animation === undefined) continue;
    const step = Math.round(bundle.step * strideFor * 1000) / 1000;
    lines.push(`\t\t\t\t${key}: {`);
    lines.push(`\t\t\t\t\tloop: ${String(animation.duration)},`);
    lines.push(`\t\t\t\t\tstep: ${String(step)},`);
    for (const channel of channels) {
      const values = animation.channels[channel];
      if (values === undefined) continue;
      lines.push(`\t\t\t\t\t${channel}: [${thin(values, strideFor).join(", ")}],`);
    }
    lines.push("\t\t\t\t},");
  }

  // The blink rides its own sampling rate. It is a half-second event inside an eight-second
  // loop, and thinning it to the bone channels' stride would smear the close into a fade —
  // the one thing a blink must not look like. It ships at the rate it was measured at.
  const blinkPeak = Math.max(
    ...Object.values(bundle.animations).map((animation) => Math.max(...(animation.blink ?? [0]))),
  );
  lines.push("\t\t\t\t/** Zero is open and `peak` is shut: the channel is a lid angle rather than");
  lines.push("\t\t\t\t *  an openness, so it is divided by `peak` before use. */");
  lines.push(`\t\t\t\tblink: { peak: ${String(blinkPeak)},`);
  for (const key of ["idle", "greet"]) {
    const animation = bundle.animations[key];
    // `Array.isArray`, not `=== undefined`: a model with no eyelash bones measures `null` for the
    // blink rather than nothing at all, and `null.map` throws — before the write, so client.js
    // silently keeps the previous block and the test suite stays green on stale data.
    if (!Array.isArray(animation?.blink)) continue;
    const values = animation.blink.map((value) => Math.round(value * 1000) / 1000);
    lines.push(`\t\t\t\t\t${key}: { loop: ${String(animation.duration)}, step: ${String(bundle.step)}, close: [${values.join(", ")}] },`);
  }
  lines.push("\t\t\t\t},");
  lines.push("\t\t\t},");
}
lines.push("\t\t};");
lines.push("\t\t/** Used for a character with no measurement of its own. */");
lines.push(`\t\tconst MOTION_DEFAULT = ${JSON.stringify(defaultCharacter)};`);
lines.push(END);

const block = lines.join("\n");

let client = readFileSync("lib/client.js", "utf8");
// Match the whole marker line, indentation and all. Searching for the markers with
// their tabs baked in made this script fail on its own output once the block had
// been re-indented — and a generator that cannot find its own markers is worse than
// no generator, because the failure reads as "already up to date".
const startMark = client.indexOf("/* MOTION-START */");
const endMark = client.indexOf("/* MOTION-END */");
if (startMark < 0 || endMark < 0) throw new Error("client.js 里没有 MOTION 标记块");
const start = client.lastIndexOf("\n", startMark) + 1;
const end = client.indexOf("\n", endMark);
if (end < start) throw new Error("MOTION 标记块首尾颠倒");
client = client.slice(0, start) + block + client.slice(end);
writeFileSync("lib/client.js", client);

const size = block.length;
console.log(`motion-literal: 写入 lib/client.js（${String(size)} 字节，${String(Object.keys(characters).length)} 位角色）`);
// Summarise the default character only — printing all eight would bury the one number worth
// seeing, which is how much of the bundle this costs.
const shown = characters[defaultCharacter];
for (const [key, strideFor] of Object.entries(stride)) {
  const animation = shown?.animations[key];
  if (animation === undefined) continue;
  const counts = channels.map((channel) => `${channel} ${String(Math.ceil(animation.channels[channel].length / strideFor) + 1)}`).join("  ");
  console.log(`  ${defaultCharacter} · ${key} (${animation.name}) step=${String(shown.step * strideFor)}s  ${counts}`);
}
