#!/usr/bin/env node
/**
 * 把 art/motion.json 的实测曲线压成一段字面量，写进 lib/client.js。
 *
 * 为什么要有这一步：插件的浏览器半边必须是**一个自包含的文件**（模块加载器一个包只收一次
 * 注册），所以它读不到 art/motion.json。曲线得进去。而抄一遍就容易漂 —— 所以这段字面量是
 * **生成**的，不是手写的，`npm run measure:motion` 之后跟着跑一次即可。
 *
 * 用法：node scripts/motion-literal.mjs
 */

import { readFileSync, writeFileSync } from "node:fs";

const START = "\t\t/* MOTION-START */";
const END = "\t\t/* MOTION-END */";

const motion = JSON.parse(readFileSync("art/motion.json", "utf8"));

/** 每 n 个采样取一个，够用且省一半以上体积。 */
const stride = { idle: 3, greet: 2 };

/** 把一串采样按 stride 抽稀，最后一点始终保留，否则循环不闭合。 */
function thin(values, step) {
  const out = [];
  for (let i = 0; i < values.length; i += step) out.push(Math.round(values[i] * 100) / 100);
  const last = Math.round(values[values.length - 1] * 100) / 100;
  if (out[out.length - 1] !== last) out.push(last);
  return out;
}

const channels = ["waist", "chest", "head"];
const lines = [];
lines.push(START);
lines.push("\t\t/**");
lines.push("\t\t * The idle and the greeting, measured from the official chibi rather than");
lines.push("\t\t * invented. GENERATED by scripts/motion-literal.mjs from art/motion.json —");
lines.push("\t\t * edit neither by hand; re-run `npm run measure:motion` and then that script.");
lines.push("\t\t *");
lines.push("\t\t * Values are bone rotations in degrees, sampled every `step` seconds and");
lines.push("\t\t * looped. `waist` drives the spine, and `chest + head` accumulate into the");
lines.push("\t\t * neck, which is how the game's own chain adds up: each bone is relative to");
lines.push("\t\t * its parent and this rig has no separate chest.");
lines.push("\t\t */");
lines.push("\t\tconst SPINE_MOTION = {");

for (const [key, strideFor] of Object.entries(stride)) {
  const animation = motion.animations[key];
  if (animation === undefined) continue;
  const step = Math.round(motion.step * strideFor * 1000) / 1000;
  lines.push(`\t\t\t${key}: {`);
  lines.push(`\t\t\t\tloop: ${String(animation.duration)},`);
  lines.push(`\t\t\t\tstep: ${String(step)},`);
  for (const channel of channels) {
    const values = animation.channels[channel];
    if (values === undefined) continue;
    lines.push(`\t\t\t\t${channel}: [${thin(values, strideFor).join(", ")}],`);
  }
  lines.push("\t\t\t},");
}
lines.push("\t\t};");
lines.push(END);

const block = lines.join("\n");

let client = readFileSync("lib/client.js", "utf8");
const start = client.indexOf(START);
const end = client.indexOf(END);
if (start < 0 || end < 0) throw new Error("client.js 里没有 MOTION 标记块");
client = client.slice(0, start) + block + client.slice(end + END.length);
writeFileSync("lib/client.js", client);

const size = block.length;
console.log(`motion-literal: 写入 lib/client.js（${String(size)} 字节）`);
for (const [key, strideFor] of Object.entries(stride)) {
  const animation = motion.animations[key];
  if (animation === undefined) continue;
  const counts = channels.map((channel) => `${channel} ${String(Math.ceil(animation.channels[channel].length / strideFor) + 1)}`).join("  ");
  console.log(`  ${key} (${animation.name}) step=${String(motion.step * strideFor)}s  ${counts}`);
}
